version: "3.1"

services:
  php-server:
    container_name: php-server
    image: quocanhbk17/php-server:0.1
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tshirt
    volumes:
      - /var/lib/db:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=db
      - PMA_PORT=3306
